### ISSUE TITLE
ODE_Output_Schema_Reference BSM locationData data as strings?

### ISSUE THREAD

**Issue by southernsun** [usdot-jpo-ode/jpo-ode#254]
In:

https://github.com/usdot-jpo-ode/jpo-ode/blob/develop/docs/ODE_Output_Schema_Reference.docx

The details in the locationData section are stored as string, why are these not stored as floats? especially the lon/lats.

**Comment by henclewood** [comment]
Southernsun,

We appreciate you reaching out to us, and working with the ODE. We will look into this issue and get back to you within 48-hours.

Best regards,

ODE Team

**Comment by southernsun** [comment]
hi, for your information, I'm part of the CV PEP team.

**Comment by musavih2** [comment]
hi @southernsun 

Please elaborate on what section of the document you see `locationData` represented as `String`. As you can see in section 3.5 of the document, they are specified as `decimal`:

```
A data structure containing the following:
   decimal latitude;
   decimal longitude;
   decimal elevation;
   decimal speed;
   decimal heading;

Latitude and longitude will be represented in degrees, elevation in meters, speed in meters per second and heading in degrees.
```
If you are referring to the sample data that encloses the values in double-quotes, that's due to some unfortunate format conversion that forced us to treat them as strings and put the values inside double-quotes. However, when you parse the data, you should be able to parse them as floats or  doubles, nonetheless.

Regards,
ODE Team

**Comment by southernsun** [comment]
> If you are referring to the sample data that encloses the values in double-quotes, that's due to some unfortunate format conversion that forced us to treat them as strings and put the values inside double-quotes. However, when you parse the data, you should be able to parse them as floats or doubles, nonetheless.

that is what i was referring too. Thanks for clarifying that.
