### ISSUE TITLE
RSU Monitor end-point likely has a memory leak

### ISSUE THREAD

**Issue by hmusavi** [usdot-jpo-ode/jpo-ode#265]
ODE container periodically runs out of memory on the WYDOT server. By running “docker stats” we are seeing that the ODE container is constantly creating PIDs (well over 1000 after a few hours). Attached are the results from “docker stats.” The top container is the ODE. Whe this happens, the ODE container crashes and the logs show errors like “There is insufficient memory for the Java Runtime Environment”. Observing docker stats, it appears that as the ODE processes RSU queries using these instructions, the memory usage grows: https://github.com/usdot-jpo-ode/jpo-ode/wiki/Query-RSU-for-set-TIMs

We have a process to query RSUs repeatedly to check that they have the TIMs that we think they should have. When we shut this process off overnight, the ODE container memory usage goes down, and the PIDs from docker stats stop increasing at the rate they had before.

Attached are some graphs showing memory usage. The top graph shows the ODE’s memory increasing until RSU query process is turned off, and going back up once resumed. The bottom graph shows the total server memory during the same time period. This shows exactly when RSU monitor is turned off. It’s a very slow increase in memory, but it is evident.

![dockerstats](https://user-images.githubusercontent.com/10130982/46507105-e0199f00-c804-11e8-8bda-41b9587f9ed2.PNG)
![odememoryode](https://user-images.githubusercontent.com/10130982/46507106-e0199f00-c804-11e8-8973-949dd7de1b46.PNG)

**Comment by mvs5465** [comment]
Upon further investigation we have determined that this is an expected consequence of using Spring. Spring REST controllers will spawn a new thread to handle requests, normally if requests come in slowly enough Spring will have time to close old threads or reuse them. 

In this case a script was hitting this endpoint with no throttle, meaning that Spring did not have enough time to close old threads and reuse them. In order to manage all of these requests, Spring kept spawning new threads. This is the desired functionality.

If queries are slow enough, the thread count will not increase dramatically. If not queried after a period of time, Spring will reduce the size of the thread pool and PID count will fall back down to acceptable levels.
